spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/db_trabalho"
    username: "postgres"
    password: "123456"
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

server:
  port: 9093
  error:
    include-message: always